services:
  - type: web
    name: rasa-actions
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 5055
    numInstances: 1
    healthCheckPath: /health
    autoDeploy: true