services:
  # Action Server
  - type: web
    name: rasa-actions
    env: docker
    docker:
      dockerfile: Dockerfile.action
    plan: free
    envVars:
      - key: PORT
        value: 5055
    numInstances: 1
    healthCheckPath: /health
    autoDeploy: true

  # Rasa Server
  - type: web
    name: rasa-core
    env: docker
    docker:
      dockerfile: Dockerfile.rasa
    plan: free
    envVars:
      - key: PORT
        value: 5005
      - key: ACTION_ENDPOINT
        value: https://rasa-actions.onrender.com/webhook
    numInstances: 1
    healthCheckPath: /
    autoDeploy: true